web:
  build: .
  command: php app/console server:run 0.0.0.0:80
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - .:/app
db:
  image: orchardup/mysql
  environment:
    MYSQL_DATABASE: symfony
